version: '3.9'
services:
  db:
    container_name: p14
    image: postgres:14-alpine
    environment:
      DATABASE_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always

  # api:
  #   container_name: api
  #   restart: always
  #   build: .
  #   ports:
  #     - ${PORT}:${PORT}
